name = "Next Garden: Next"
author = "Mod Garden"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
unsup = "1.2.0"
unsup-experimental = "1.2.0"
unsup-stable = "1.2.0"

[options]
datapack-folder = "resources/datapack/required"
no-internal-hashes = true
